#!/bin/bash
# MathSpeak Shortcut Setup Script for Arch Linux

echo "🎯 MathSpeak Shortcut Setup"
echo "=========================="
echo ""

# Get the full path to mathspeak
MATHSPEAK_DIR="$(cd "$(dirname "$0")" && pwd)"
MATHSPEAK_PATH="$MATHSPEAK_DIR/mathspeak.py"
PYTHON_CMD="python"

# Check if mathspeak.py exists
if [ ! -f "$MATHSPEAK_PATH" ]; then
    echo "❌ Error: mathspeak.py not found at $MATHSPEAK_PATH"
    exit 1
fi

echo "Found MathSpeak at: $MATHSPEAK_PATH"
echo ""
echo "Choose your preferred setup method:"
echo ""
echo "1) Alias in ~/.bashrc (recommended)"
echo "2) Shell script in ~/bin/"
echo "3) Shell script in /usr/local/bin/ (system-wide)"
echo "4) All of the above"
echo ""
read -p "Enter your choice (1-4): " choice

# Function to create alias
create_alias() {
    echo ""
    echo "📝 Creating alias in ~/.bashrc..."
    
    # Remove old ms alias if exists
    sed -i '/alias ms=/d' ~/.bashrc 2>/dev/null
    
    # Add new alias
    echo "" >> ~/.bashrc
    echo "# MathSpeak shortcut" >> ~/.bashrc
    echo "alias ms='$PYTHON_CMD $MATHSPEAK_PATH'" >> ~/.bashrc
    
    echo "✅ Alias added to ~/.bashrc"
    echo ""
    echo "To use immediately, run: source ~/.bashrc"
}

# Function to create shell script
create_shell_script() {
    local install_dir=$1
    local script_path="$install_dir/ms"
    
    echo ""
    echo "📝 Creating shell script at $script_path..."
    
    # Create directory if needed
    mkdir -p "$install_dir" 2>/dev/null
    
    # Create the script
    cat > "$script_path" << EOF
#!/bin/bash
# MathSpeak shortcut script
# Auto-generated by setup_ms_shortcut.sh

# Full path to MathSpeak
MATHSPEAK_PATH="$MATHSPEAK_PATH"

# Pass all arguments to mathspeak
$PYTHON_CMD "\$MATHSPEAK_PATH" "\$@"
EOF
    
    # Make executable
    chmod +x "$script_path"
    
    echo "✅ Script created at $script_path"
    
    # Add to PATH if needed
    if [[ "$install_dir" == "$HOME/bin" ]] && [[ ":$PATH:" != *":$HOME/bin:"* ]]; then
        echo ""
        echo "⚠️  Note: ~/bin is not in your PATH"
        echo "   Add this to ~/.bashrc: export PATH=\"\$HOME/bin:\$PATH\""
    fi
}

# Execute based on choice
case $choice in
    1)
        create_alias
        ;;
    2)
        create_shell_script "$HOME/bin"
        ;;
    3)
        if [ -w "/usr/local/bin" ]; then
            create_shell_script "/usr/local/bin"
        else
            echo "⚠️  Need sudo for /usr/local/bin"
            sudo bash -c "$(declare -f create_shell_script); create_shell_script /usr/local/bin"
        fi
        ;;
    4)
        create_alias
        create_shell_script "$HOME/bin"
        if [ -w "/usr/local/bin" ]; then
            create_shell_script "/usr/local/bin"
        else
            echo "⚠️  Need sudo for /usr/local/bin"
            sudo bash -c "$(declare -f create_shell_script); create_shell_script /usr/local/bin"
        fi
        ;;
    *)
        echo "❌ Invalid choice"
        exit 1
        ;;
esac

echo ""
echo "🎉 Setup complete!"
echo ""
echo "Usage examples:"
echo '  ms "x^2 + y^2 = r^2"'
echo '  ms "\int_0^\infty e^{-x^2} dx"'
echo '  ms "\pi_1(S^1) \cong \mathbb{Z}" --save'
echo '  ms --interactive'
echo '  ms --help'
echo ""

# Test if ms command exists
if command -v ms &> /dev/null; then
    echo "✅ The 'ms' command is now available!"
else
    echo "⚠️  The 'ms' command is not yet available in this shell."
    echo "   Run: source ~/.bashrc"
    echo "   Or open a new terminal"
fi